/****************************************************************************
 *
 *    ****                              I
 *   ******                            ***
 *   *******                           ****
 *   ********    ****  ****     **** *********    ******* ****    ***********
 *   *********   ****  ****     **** *********  **************  *************
 *   **** *****  ****  ****     ****   ****    *****    ****** *****     ****
 *   ****  ***** ****  ****     ****   ****   *****      ****  ****      ****
 *  ****    *********  ****     ****   ****   ****       ****  ****      ****
 *  ****     ********  ****    ****I  ****    *****     *****  ****      ****
 *  ****      ******   ***** ******   *****    ****** *******  ****** *******
 *  ****        ****   ************    ******   *************   *************
 *  ****         ***     ****  ****     ****      *****  ****     *****  ****
 *                                                                       ****
 *          I N N O V A T I O N  T O D A Y  F O R  T O M M O R O W       ****
 *                                                                        ***
 *
 ************************************************************************//**
 *
 * @file       cce.h
 * @brief      CCE defines
 *
 * Copyright (C) 2014, Nutaq, Canada. All rights reserved.
 *
 * This file is part of Nutaq’s BAS Software Suite.
 *
 * You may at your option receive a license to Nutaq’s BAS Software Suite under
 * either the terms of the GNU General Public License (GPL) or the
 * Nutaq Professional License, as explained in the note below.
 *
 * Nutaq’s BAS Software Suite may be used under the terms of the GNU General
 * Public License version 3 as published by the Free Software Foundation
 * and appearing in the file LICENSE.GPL included in the packaging of this file.
 *
 * Nutaq’s BAS Software Suite is provided AS IS WITHOUT WARRANTY OF
 * ANY KIND; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * NOTE:
 *
 * Using Nutaq’s BAS Software Suite under the GPL requires that your work based on
 * Nutaq’s BAS Software Suite, if  distributed, must be licensed under the GPL.
 * If you wish to distribute a work based on Nutaq’s BAS Software Suite but desire
 * to license it under your own terms, e.g. a closed source license, you may purchase
 * a Nutaq Professional License.
 *
 * The Professional License, gives you -- under certain conditions -- the right to
 * use any license you wish for your work based on Nutaq’s BAS Software Suite.
 * For the full terms of the Professional License, please contact the Nutaq sales team.
 *
 ****************************************************************************/

#ifndef __ADP_CCE__
#define __ADP_CCE__

#ifdef __cplusplus
extern "C" {
#endif

#include "bas_error.h"

#define CCEIPPORT 19836
#define CCEDETECTPORT 19837
#define CCE_DETECT_ADDR "239.29.29.1"

#define CCE_ECHO_REQUEST "ADPECHOPING"
#define CCE_ECHO_RESPONSE "ADPECHOPONG"

//COMMANDS
#define MAKECMD(module, cmd) ((module)<<16 | (cmd))

//ECHO
#define ECHO 0x0
#define ECHO_ECHO MAKECMD(ECHO, 0x0)

//CTRL
#define CCECTRL 0x1
#define CCECTRL_EXIT MAKECMD(CCECTRL, 0x1)
#define CCECTRL_VERSION MAKECMD(CCECTRL, 0x2)
#define CCECTRL_MODE2_INIT MAKECMD(CCECTRL, 0x10)
#define CCECTRL_NORMAL_MODE MAKECMD(CCECTRL, 0x11)
#define CCECTRL_TURBO_MODE MAKECMD(CCECTRL, 0x12)
#define CCECTRL_GET_MAC MAKECMD(CCECTRL, 0x20)

//FPGA FLASH
#define FPGAFLASH 0x2
#define FPGAFLASH_INIT MAKECMD(FPGAFLASH, 0x1)
#define FPGAFLASH_RECV MAKECMD(FPGAFLASH, 0x2)
#define FPGAFLASH_RECVWID MAKECMD(FPGAFLASH, 0x3)
#define FPGAFLASH_GET_INDEX MAKECMD(FPGAFLASH, 0x4)
#define FPGAFLASH_SET_INDEX MAKECMD(FPGAFLASH, 0x5)
#define FPGAFLASH_GET_INFO MAKECMD(FPGAFLASH, 0x6)
#define FPGAFLASH_UPDATE_RECV MAKECMD(FPGAFLASH, 0x7)
#define FPGAFLASH_DTB_RECV MAKECMD(FPGAFLASH, 0x8)

//BUS ACCESS
#define MEMORY 0x3
#define MEMORY_INIT MAKECMD(MEMORY, 0x1)
#define MEMORY_READ MAKECMD(MEMORY, 0x2)
#define MEMORY_WRITE MAKECMD(MEMORY, 0x3)
#define MEMORY_READ_WITH_ID MAKECMD(MEMORY, 0x4)
#define MEMORY_WRITE_WITH_ID MAKECMD(MEMORY, 0x5)
#define MEMORY_READ_CUSTOM_REG_ID MAKECMD(MEMORY, 0x6)
#define MEMORY_WRITE_CUSTOM_REG_ID MAKECMD(MEMORY, 0x7)
#define MEMORY_SCAN_I2C_DEVICES MAKECMD(MEMORY, 0x8)
#define MEMORY_WRITE_WITH_MASK MAKECMD(MEMORY, 0x9)

//ADAC250
#define ADAC250 0x4
#define ADAC250_PRESENCE MAKECMD(ADAC250, 0x1)
#define ADAC250_POWERUP MAKECMD(ADAC250, 0x2)
#define ADAC250_READSPI MAKECMD(ADAC250, 0x3)
#define ADAC250_WRITESPI MAKECMD(ADAC250, 0x4)
//ADAC250 - PLL
#define ADAC250_INITPLL MAKECMD(ADAC250, 0x12)
#define ADAC250_CALCULATEPLLPARAMS MAKECMD(ADAC250, 0x13)
#define ADAC250_SETPLLCONFIG MAKECMD(ADAC250, 0x14)
#define ADAC250_TRIGPLLREGISTERTRANSFERT MAKECMD(ADAC250, 0x15)
#define ADAC250_PLLSYNCOUTPUT MAKECMD(ADAC250, 0x16)
#define ADAC250_GETPLLSTATUS MAKECMD(ADAC250, 0x17)
#define ADAC250_SETPLLSLEEP MAKECMD(ADAC250, 0x18)
#define ADAC250_SETREFCLKTUNING MAKECMD(ADAC250, 0x19)
//ADAC250 - DAC
#define ADAC250_DACINIT MAKECMD(ADAC250, 0x30)
#define ADAC250_DACSETGAIN MAKECMD(ADAC250, 0x31)
#define ADAC250_DACSETOFFSET MAKECMD(ADAC250, 0x32)
#define ADAC250_SETDACDDSFREQ MAKECMD(ADAC250, 0x33)
#define ADAC250_SETDACDDSDOWNSAMPLER MAKECMD(ADAC250, 0x34)
#define ADAC250_SETDACDATASOURCE MAKECMD(ADAC250, 0x35)
#define ADAC250_DACSYNC MAKECMD(ADAC250, 0x36)
#define ADAC250_DACCALIBRATE MAKECMD(ADAC250, 0x37)
#define ADAC250_DACSYNCSOURCE MAKECMD(ADAC250, 0x38)
//ADAC250 - ADC
#define ADAC250_INITADC MAKECMD(ADAC250, 0x50)
//#define ADAC250_SETADCCONFIG MAKECMD(ADAC250, 0x51)
#define ADAC250_SETADCGAIN MAKECMD(ADAC250, 0x52)
#define ADAC250_SETADCFINEGAIN MAKECMD(ADAC250, 0x53)
#define ADAC250_SETADCPEDESTAL MAKECMD(ADAC250, 0x54)
#define ADAC250_GETADCSTATUS MAKECMD(ADAC250, 0x55)
#define ADAC250_ADCCALIBRATE MAKECMD(ADAC250, 0x56)
#define ADAC250_SETADCDATAFORMAT MAKECMD(ADAC250, 0x57)
#define ADAC250_SETADCSLEEPMODE MAKECMD(ADAC250, 0x58)
#define ADAC250_SETADCOFFSETCORRECTIONTIME MAKECMD(ADAC250, 0x59)
#define ADAC250_SETADCTRIGGERDELAY MAKECMD(ADAC250, 0x5A)
//ADAC250 - MUX
#define ADAC250_SETMUX MAKECMD(ADAC250, 0x70)

//TTRFT
#define TTRFT 0x5
#define TTRFT_INIT MAKECMD(TTRFT, 0x1)
#define TTRFT_RESET MAKECMD(TTRFT, 0x2)
#define TTRFT_SETPLLPARAM MAKECMD(TTRFT, 0x3)
#define TTRFT_FINDPARAM MAKECMD(TTRFT, 0x4)
#define TTRFT_SETMAINPOWER MAKECMD(TTRFT, 0x5)
#define TTRFT_SETTXRXPOWER MAKECMD(TTRFT, 0x6)
#define TTRFT_SETTXPRESCALER MAKECMD(TTRFT, 0x7)
#define TTRFT_GETPLLLOCK MAKECMD(TTRFT, 0x8)
#define TTRFT_SETRXFILTER MAKECMD(TTRFT, 0x9)
#define TTRFT_SETREFCLK MAKECMD(TTRFT, 0xA)
#define TTRFT_SETLED MAKECMD(TTRFT, 0xB)
#define TTRFT_SETRXFREQ MAKECMD(TTRFT, 0xC)
#define TTRFT_SETTXFREQ MAKECMD(TTRFT, 0xD)
#define TTRFT_SETTXPOWER MAKECMD(TTRFT, 0xE)
#define TTRFT_SETRXPOWER MAKECMD(TTRFT, 0xF)

//TWRFT
#define TWRFT 0x6
#define TWRFT_INIT MAKECMD(TWRFT, 0x1)
#define TWRFT_RESET MAKECMD(TWRFT, 0x2)
#define TWRFT_TXRXMODE MAKECMD(TWRFT, 0x3)
#define TWRFT_RXAGCMODE MAKECMD(TWRFT, 0x4)
#define TWRFT_RXLNA MAKECMD(TWRFT, 0x5)
#define TWRFT_TXGAIN MAKECMD(TWRFT, 0x6)
#define TWRFT_BOARDTEMP MAKECMD(TWRFT, 0x7)
#define TWRFT_TXPOWER MAKECMD(TWRFT, 0x8)
#define TWRFT_SETPLLPARAM MAKECMD(TWRFT, 0x9)
#define TWRFT_FINDPLLPARAM MAKECMD(TWRFT, 0xA)
#define TWRFT_RXAGCGAINDB MAKECMD(TWRFT, 0xB)
#define TWRFT_RXAGCGAIN MAKECMD(TWRFT, 0xC)
#define TWRFT_GETPLLLOCK MAKECMD(TWRFT, 0xD)
#define TWRFT_SETREFCLK MAKECMD(TWRFT, 0xE)
#define TWRFT_SETLED MAKECMD(TWRFT, 0xF)

//FMC RADIO
#define FMCRADIO 0x8
#define FMCRADIO_INIT MAKECMD(FMCRADIO, 0x1)
#define FMCRADIO_RESET MAKECMD(FMCRADIO, 0x2)
#define FMCRADIO_SPIWRITE MAKECMD(FMCRADIO, 0x3)
#define FMCRADIO_SPIREAD MAKECMD(FMCRADIO, 0x4)
#define FMCRADIO_SETBAND MAKECMD(FMCRADIO, 0x5)
#define FMCRADIO_SETRXGAIN MAKECMD(FMCRADIO, 0x6)
#define FMCRADIO_SETTXGAIN MAKECMD(FMCRADIO, 0x7)
#define FMCRADIO_SETTXAUTOGAIN MAKECMD(FMCRADIO, 0x8)
//#define FMCRADIO_SETIOX MAKECMD(FMCRADIO, 0x8)
#define FMCRADIO_POWERUP MAKECMD(FMCRADIO, 0x9)
#define FMCRADIO_SELECT MAKECMD(FMCRADIO, 0xa)
#define FMCRADIO_SETREVISION MAKECMD(FMCRADIO, 0xb)
#define FMCRADIO_PLLCALCULATE MAKECMD(FMCRADIO, 0x11)
#define FMCRADIO_PLLCALCULATEPFD MAKECMD(FMCRADIO, 0x12)
#define FMCRADIO_PLLSETPARAM MAKECMD(FMCRADIO, 0x13)
#define FMCRADIO_PLLLOCKSTATUS MAKECMD(FMCRADIO, 0x14)
#define FMCRADIO_PLLWAITLOCK MAKECMD(FMCRADIO, 0x15)
#define FMCRADIO_CLOCKMUXSET MAKECMD(FMCRADIO, 0x20)
#define FMCRADIO_LIMECALCULATE MAKECMD(FMCRADIO, 0x30)
#define FMCRADIO_LIMESETPLLPARAM MAKECMD(FMCRADIO, 0x31)
#define FMCRADIO_LIMERESET MAKECMD(FMCRADIO, 0x32)
#define FMCRADIO_LIMEPLLCALIBRATE MAKECMD(FMCRADIO, 0x33)
#define FMCRADIO_RXFILTER MAKECMD(FMCRADIO, 0x40)
#define FMCRADIO_LPFSET MAKECMD(FMCRADIO, 0x50)
#define FMCRADIO_LPFCALIBRATE MAKECMD(FMCRADIO, 0x51)
#define FMCRADIO_RXVGACALIBRATE MAKECMD(FMCRADIO, 0x52)
#define FMCRADIO_ENABLEPATH MAKECMD(FMCRADIO, 0x60)
#define FMCRADIO_DISABLEPATH MAKECMD(FMCRADIO, 0x61)
#define FMCRADIO_LOOPBACK MAKECMD(FMCRADIO, 0x62)
#define FMCRADIO_LO_CALIBRATE MAKECMD(FMCRADIO, 0x70)
#define FMCRADIO_LO_CALIBRATE_SET MAKECMD(FMCRADIO, 0x71)
#define FMCRADIO_SSB_CALIBRATE MAKECMD(FMCRADIO, 0x72)
#define FMCRADIO_SSB_CALIBRATE_SET MAKECMD(FMCRADIO, 0x73)
#define FMCRADIO_RXFE_DC_CALIBRATE MAKECMD(FMCRADIO, 0x74)
#define FMCRADIO_RXFE_DC_CALIBRATE_SET MAKECMD(FMCRADIO, 0x75)
#define FMCRADIO_SPI_CONTROL_SET MAKECMD(FMCRADIO, 0x76)
#define FMCRADIO_RX_CONNECT_SET MAKECMD(FMCRADIO, 0x77)
#define FMCRADIO_RX_DISCONNECT_SET MAKECMD(FMCRADIO, 0x78)

//FPGA RADIO
#define FPGACONTROL 0x9
#define FPGACONTROL_CONFIGURE_FROM_FLASH MAKECMD(FPGACONTROL, 0x1)
#define FPGACONTROL_CONFIGURE_FROM_FILE MAKECMD(FPGACONTROL, 0x2)
#define FPGACONTROL_VERIFY MAKECMD(FPGACONTROL, 0x3)
#define FPGACONTROL_RESET MAKECMD(FPGACONTROL, 0x4)

//PLL CONFIG
#define PLLCONFIG 0xA
#define PLLCONFIG_FLASH_FROM_FILE MAKECMD(PLLCONFIG, 0x1)
#define PLLCONFIG_CONFIG_FROM_FLASH MAKECMD(PLLCONFIG, 0x2)
#define PLLCONFIG_CONFIG_FROM_FILE MAKECMD(PLLCONFIG, 0x3)
#define PLLCONFIG_CONFIG_GET MAKECMD(PLLCONFIG, 0x4)

//CARRIER
#define CARRIER 0xB
#define CARRIER_PRESENCE                    MAKECMD(CARRIER, 0x01)
#define CARRIER_GETTYPE                     MAKECMD(CARRIER, 0x08)

#define CARRIER_GETMODULEBASEADDR           MAKECMD(CARRIER, 0x10)
#define CARRIER_LEDSETVALUE                 MAKECMD(CARRIER, 0x11)
#define CARRIER_LEDGETVALUE                 MAKECMD(CARRIER, 0x12)
#define CARRIER_TCLKSETSTATE                MAKECMD(CARRIER, 0x13)
#define CARRIER_TCLKGETSTATE                MAKECMD(CARRIER, 0x14)
#define CARRIER_TCLKSETTXSOURCE             MAKECMD(CARRIER, 0x15)
#define CARRIER_TCLKGETTXSOURCE             MAKECMD(CARRIER, 0x16)
#define CARRIER_FMCBIDIRCLKSETCONNECTION    MAKECMD(CARRIER, 0x17)
#define CARRIER_FMCBIDIRCLKGETCONNECTION    MAKECMD(CARRIER, 0x18)
#define CARRIER_SETOSCSTATE                 MAKECMD(CARRIER, 0x19)
#define CARRIER_GETOSCSTATE                 MAKECMD(CARRIER, 0x1A)
#define CARRIER_FCLKASETCONNECTION          MAKECMD(CARRIER, 0x1B)
#define CARRIER_FCLKAGETCONNECTION          MAKECMD(CARRIER, 0x1C)
#define CARRIER_I2CREAD                     MAKECMD(CARRIER, 0x1D)
#define CARRIER_I2CWRITE                    MAKECMD(CARRIER, 0x1E)
#define CARRIER_I2CREADNOWRDATA             MAKECMD(CARRIER, 0x1F)

#define CARRIER_REBOOT                      MAKECMD(CARRIER, 0x20)

//ADC5000
#define ADC5000 0xC
#define ADC5000_PRESENCE MAKECMD(ADC5000, 0x1)
#define ADC5000_POWERUP MAKECMD(ADC5000, 0x2)
#define ADC5000_RESET MAKECMD(ADC5000, 0x3)
#define ADC5000_SET_MODE MAKECMD(ADC5000, 0x4)
#define ADC5000_SET_PLL_PARAM MAKECMD(ADC5000, 0x5)
#define ADC5000_SET_SYNC MAKECMD(ADC5000, 0x6)
#define ADC5000_PLL_LOCK MAKECMD(ADC5000, 0x7)
//#define ADC5000_READ_TEMPERATURE MAKECMD(ADC5000, 0x8)
#define ADC5000_SET_TEST_MODE MAKECMD(ADC5000, 0x9)
#define ADC5000_CALIBRATE_IODELAY MAKECMD(ADC5000, 0xA)
#define ADC5000_GET_ADC_STATUS MAKECMD(ADC5000, 0xB)
#define ADC5000_SET_STANDBY MAKECMD(ADC5000, 0xC)
#define ADC5000_SET_CODING MAKECMD(ADC5000, 0xD)
#define ADC5000_SET_BANDWIDTH MAKECMD(ADC5000, 0xE)
#define ADC5000_SET_ADJ_TRIGGER_DELAY MAKECMD(ADC5000, 0xF)
#define ADC5000_SET_OFFSET MAKECMD(ADC5000, 0x10)
#define ADC5000_SET_GAIN MAKECMD(ADC5000, 0x11)
#define ADC5000_SET_PHASE MAKECMD(ADC5000, 0x12)

//MI125
#define MI125 0xD
#define MI125_INIT MAKECMD(MI125, 0x1)
#define MI125_POWERUP MAKECMD(MI125, 0x2)
#define MI125_MI125_RESET MAKECMD(MI125, 0x3)
#define MI125_MI125_DIGITAL_ADCCALIBRATION MAKECMD(MI125, 0x4)
#define MI125_MI125_SET_CONFIG MAKECMD(MI125, 0x5)
#define MI125_MI125_SET_CLKSRC MAKECMD(MI125, 0x6)
#define MI125_MI125_CHECKCORE MAKECMD(MI125, 0x7)
#define MI125_MI125_SET_TESTMODE MAKECMD(MI125, 0x8)
#define MI125_MI125_GET_TEMPERATURE MAKECMD(MI125, 0x9)
#define MI125_MI125_GET_CHANNELCALIBSTATUS MAKECMD(MI125, 0xa)
#define MI125_MI125_GET_VERSIONS MAKECMD(MI125, 0xb)
#define MI125_MI125_CHECKADC MAKECMD(MI125, 0xc)
#define MI125_MI125_SET_TRIGOUT MAKECMD(MI125, 0xd)
#define MI125_MI125_GET_CLKMASTER MAKECMD(MI125, 0xe)
#define MI125_MI125_CLOCKRESET MAKECMD(MI125, 0xf)
#define MI125_MI125_SCAN_I2C MAKECMD(MI125, 0x10)
#define MI125_MI125_TEST_LOCALOSCSW MAKECMD(MI125, 0x11)

//FMC LVDS
#define FMCLVDS 0xE
#define FMCLVDS_INIT MAKECMD(FMCLVDS, 0x1)
#define FMCLVDS_POWERUP MAKECMD(FMCLVDS, 0x2)
//#define FMCLVDS_SETREVISION MAKECMD(FMCLVDS, 0x3)
#define FMCLVDS_PRESENCE MAKECMD(FMCLVDS, 0x4)
#define FMCLVDS_SELECT MAKECMD(FMCLVDS, 0x5)
#define FMCLVDS_SETDIR MAKECMD(FMCLVDS, 0x6)
#define FMCLVDS_SET_CHANNEL_PWDN MAKECMD(FMCLVDS, 0x7)
#define FMCLVDS_SET_CHANNEL_PREEMP MAKECMD(FMCLVDS, 0x8)

//MI250
#define MI250 0xF
#define MI250_INIT MAKECMD(MI250, 0x1)
#define MI250_POWERUP MAKECMD(MI250, 0x2)
#define MI250_PRESENCE MAKECMD(MI250, 0x3)
#define MI250_READSPI MAKECMD(MI250, 0x4)
#define MI250_WRITESPI MAKECMD(MI250, 0x5)
#define MI250_PLLCONFIG MAKECMD(MI250, 0x6)
#define MI250_GETPLLSTATUS MAKECMD(MI250, 0x7)
//#define MI250_SETADCCONFIG MAKECMD(MI250, 0x8)
#define MI250_SETADCGAIN MAKECMD(MI250, 0x9)
#define MI250_SETADCFINEGAIN MAKECMD(MI250, 0xA)
#define MI250_SETADCPEDESTAL MAKECMD(MI250, 0xB)
//define MI250_GETADCSTATUS MAKECMD(MI250, 0xC)
#define MI250_ADCRESET MAKECMD(MI250, 0xD)
#define MI250_ARMADC MAKECMD(MI250, 0xE)
#define MI250_SETDATAFORMAT MAKECMD(MI250, 0x11)
#define MI250_SETSLEEPMODE MAKECMD(MI250, 0x12)
#define MI250_SETOCT MAKECMD(MI250, 0x13)
#define MI250_SELECT MAKECMD(MI250, 0x14)

//AURORA
#define AURORA 0x10
#define AURORA_GETVERSION             MAKECMD(AURORA, 0x1)
#define AURORA_RESETCORE              MAKECMD(AURORA, 0x2)
#define AURORA_GETCHANNELSTATUS       MAKECMD(AURORA, 0x3)
#define AURORA_RESETRXFIFO            MAKECMD(AURORA, 0x4)
#define AURORA_RESETTXFIFO            MAKECMD(AURORA, 0x5)
#define AURORA_GETRXDATACOUNT         MAKECMD(AURORA, 0x6)
#define AURORA_GETTXDATACOUNT         MAKECMD(AURORA, 0x7)
#define AURORA_GETRXDATARATE          MAKECMD(AURORA, 0x8)
#define AURORA_GETTXDATARATE          MAKECMD(AURORA, 0x9)
#define AURORA_SETGTXTXPARAM          MAKECMD(AURORA, 0xA)
#define AURORA_GETGTXTXPARAM          MAKECMD(AURORA, 0xB)
#define AURORA_SETGTXRXPARAM          MAKECMD(AURORA, 0xC)
#define AURORA_GETGTXRXPARAM          MAKECMD(AURORA, 0xD)
#define AURORA_GETDFEEYEDACMON        MAKECMD(AURORA, 0xE)
#define AURORA_SETCHANNELENABLESTATE  MAKECMD(AURORA, 0xF)
#define AURORA_GETCHANNELENABLESTATE  MAKECMD(AURORA, 0x10)

//PPSSYNC
#define PPSSYNC 0x11
#define PPSSYNC_PRESENCE    MAKECMD(PPSSYNC, 0x1)
#define PPSSYNC_CONFIGURE	MAKECMD(PPSSYNC, 0x2)
#define PPSSYNC_START		MAKECMD(PPSSYNC, 0x3)
#define PPSSYNC_STOP		MAKECMD(PPSSYNC, 0x4)
#define PPSSYNC_GETINFO		MAKECMD(PPSSYNC, 0x5)
#define PPSSYNC_SAVEDAC		MAKECMD(PPSSYNC, 0x6)
#define PPSSYNC_READDAC		MAKECMD(PPSSYNC, 0x7)
#define PPSSYNC_SAVEPROFILE	MAKECMD(PPSSYNC, 0x8)
#define PPSSYNC_READPROFILE	MAKECMD(PPSSYNC, 0x9)
#define PPSSYNC_DACINIT		MAKECMD(PPSSYNC, 0xa)


//LVDS
#define LVDS_COMMAND 0x12
#define LVDS_PRESENCE           MAKECMD(LVDS_COMMAND, 0x1)
#define LVDS_GETMODE            MAKECMD(LVDS_COMMAND, 0x2)
#define LVDS_SETOUTPUTENABLE    MAKECMD(LVDS_COMMAND, 0x3)
#define LVDS_SETVALUE           MAKECMD(LVDS_COMMAND, 0x4)
#define LVDS_GETVALUE           MAKECMD(LVDS_COMMAND, 0x5)
#define LVDS_RESET              MAKECMD(LVDS_COMMAND, 0x6)
#define LVDS_RESET_FIFO         MAKECMD(LVDS_COMMAND, 0x7)

#define SYSMON_COMMAND 0x13
#define SYSMON_READ             MAKECMD(SYSMON_COMMAND, 0x1)

//MO1000
#define MO1000 0x14
#define MO1000_PRESENCE MAKECMD(MO1000, 0x1)
#define MO1000_POWERUP MAKECMD(MO1000, 0x2)
#define MO1000_RESET MAKECMD(MO1000, 0x3)
#define MO1000_INIT MAKECMD(MO1000, 0x4)
#define MO1000_WRITEREG MAKECMD(MO1000, 0x5)
#define MO1000_READREG MAKECMD(MO1000, 0x6)
#define MO1000_GETSTATUS MAKECMD(MO1000, 0x7)
#define MO1000_GETTEMPERATURE MAKECMD(MO1000, 0x8)
#define MO1000_SETCLOCKCONFIG MAKECMD(MO1000, 0x9)
#define MO1000_DODACCALIBRATION MAKECMD(MO1000, 0xA)
#define MO1000_GETCHANNELCALIBSTATUS MAKECMD(MO1000, 0xB)
#define MO1000_SETDACOUTCTRL MAKECMD(MO1000, 0xC)
#define MO1000_SETDACPARINTERPOLATION MAKECMD(MO1000, 0xD)
#define MO1000_SETDACPARDCOFFSET MAKECMD(MO1000, 0xE)
#define MO1000_SETDACPARGAIN MAKECMD(MO1000, 0xF)
#define MO1000_DODACUPDATE MAKECMD(MO1000, 0x10)
#define MO1000_SETDACPARACTCHANNEL MAKECMD(MO1000, 0x11)
#define MO1000_GETCLKMASTER MAKECMD(MO1000, 0x12)
#define MO1000_SETDACPARISINC MAKECMD(MO1000, 0x13)
#define MO1000_SETDACPARISINCCTRL MAKECMD(MO1000, 0x14)
#define MO1000_SETDACPARFINEMOD MAKECMD(MO1000, 0x15)
#define MO1000_SETDACPARFINEMODCTRL MAKECMD(MO1000, 0x16)
#define MO1000_SETDACPARDATAFORMAT MAKECMD(MO1000, 0x17)
#define MO1000_SETDACPARQUADPHASE MAKECMD(MO1000, 0x18)
#define MO1000_GETVERSIONS MAKECMD(MO1000, 0x19)
#define MO1000_TESTLOCALOSCSW MAKECMD(MO1000, 0x1A)
#define MO1000_TESTBRIDGERESET MAKECMD(MO1000, 0x1B)
#define MO1000_TESTDACRESET MAKECMD(MO1000, 0x1C)
#define MO1000_TESTPLLSEL MAKECMD(MO1000, 0x1D)
#define MO1000_TESTPLLPOWDOWN MAKECMD(MO1000, 0x1E)
#define MO1000_TESTPLLSYNC MAKECMD(MO1000, 0x1F)
#define MO1000_TESTDACIRQ MAKECMD(MO1000, 0x20)
#define MO1000_TESTDACCLKS MAKECMD(MO1000, 0x21)
#define MO1000_TESTDCIFRAME MAKECMD(MO1000, 0x22)
#define MO1000_CHECKI2C MAKECMD(MO1000, 0x23)
#define MO1000_GETCOREFREQUENCY MAKECMD(MO1000, 0x24)
#define MO1000_SETTESTMODE MAKECMD(MO1000, 0x25)
#define MO1000_WRITECLOCKCONFIG MAKECMD(MO1000, 0x26)
#define MO1000_GETPLLCONFIG MAKECMD(MO1000, 0x27)
#define MO1000_SETPLLCONFIG MAKECMD(MO1000, 0x28)

//TIMESTAMP
#define TIMESTAMP 0x15
#define TIMESTAMP_PRESENCE MAKECMD(TIMESTAMP, 0x1)
#define TIMESTAMP_SETTIME MAKECMD(TIMESTAMP, 0x2)
#define TIMESTAMP_GETTIME MAKECMD(TIMESTAMP, 0x3)
#define TIMESTAMP_RESET MAKECMD(TIMESTAMP, 0x4)

//RTDEXSYNC
#define RTDEXSYNC 0x16
#define RTDEXSYNC_PRESENCE      MAKECMD(RTDEXSYNC, 0x1)
#define RTDEXSYNC_CORERESET     MAKECMD(RTDEXSYNC, 0x2)
#define RTDEXSYNC_CHANNELRESET  MAKECMD(RTDEXSYNC, 0x3)
#define RTDEXSYNC_CHANNELSTART  MAKECMD(RTDEXSYNC, 0x4)
#define RTDEXSYNC_CHANNELSTOP   MAKECMD(RTDEXSYNC, 0x5)
#define RTDEXSYNC_CHANNELINFO   MAKECMD(RTDEXSYNC, 0x6)

//FMCOMMS3
#define FMCOMMS3                                0x17
#define FMCOMMS3_PRESENCE                       MAKECMD(FMCOMMS3, 0x1)
#define FMCOMMS3_POWERUP                        MAKECMD(FMCOMMS3, 0x2)
#define FMCOMMS3_INIT                           MAKECMD(FMCOMMS3, 0x3)
#define FMCOMMS3_SET_EN_STATE_MACHINE_MODE      MAKECMD(FMCOMMS3, 0x4)
#define FMCOMMS3_GET_EN_STATE_MACHINE_MODE      MAKECMD(FMCOMMS3, 0x5)
#define FMCOMMS3_SET_SAMPLING_FREQ              MAKECMD(FMCOMMS3, 0x6)
#define FMCOMMS3_GET_SAMPLING_FREQ              MAKECMD(FMCOMMS3, 0x7)
#define FMCOMMS3_SET_TX_LO_FREQ                 MAKECMD(FMCOMMS3, 0x8)
#define FMCOMMS3_GET_TX_LO_FREQ                 MAKECMD(FMCOMMS3, 0x9)
#define FMCOMMS3_SET_RX_RF_GAIN                 MAKECMD(FMCOMMS3, 0xA)
#define FMCOMMS3_GET_RX_RF_GAIN                 MAKECMD(FMCOMMS3, 0xB)
#define FMCOMMS3_SET_RX_RF_BANDWIDTH            MAKECMD(FMCOMMS3, 0xC)
#define FMCOMMS3_GET_RX_RF_BANDWIDTH            MAKECMD(FMCOMMS3, 0xD)
#define FMCOMMS3_SET_RX_LO_FREQ                 MAKECMD(FMCOMMS3, 0xE)
#define FMCOMMS3_GET_RX_LO_FREQ                 MAKECMD(FMCOMMS3, 0xF)
#define FMCOMMS3_GET_RX_RSSI                    MAKECMD(FMCOMMS3, 0x10)
#define FMCOMMS3_SET_RX_GAIN_CONTROL_MODE       MAKECMD(FMCOMMS3, 0x11)
#define FMCOMMS3_GET_RX_GAIN_CONTROL_MODE       MAKECMD(FMCOMMS3, 0x12)
#define FMCOMMS3_SET_RX_FIR_CONFIG              MAKECMD(FMCOMMS3, 0x13)
#define FMCOMMS3_GET_RX_FIR_CONFIG              MAKECMD(FMCOMMS3, 0x14)
#define FMCOMMS3_SET_RX_FIR_EN_DIS              MAKECMD(FMCOMMS3, 0x15)
#define FMCOMMS3_GET_RX_FIR_EN_DIS              MAKECMD(FMCOMMS3, 0x16)
#define FMCOMMS3_SET_RX_RFDC_TRACK_EN_DIS       MAKECMD(FMCOMMS3, 0x17)
#define FMCOMMS3_GET_RX_RFDC_TRACK_EN_DIS       MAKECMD(FMCOMMS3, 0x18)
#define FMCOMMS3_SET_RX_BBDC_TRACK_EN_DIS       MAKECMD(FMCOMMS3, 0x19)
#define FMCOMMS3_GET_RX_BBDC_TRACK_EN_DIS       MAKECMD(FMCOMMS3, 0x1A)
#define FMCOMMS3_SET_RX_QUAD_TRACK_EN_DIS       MAKECMD(FMCOMMS3, 0x1B)
#define FMCOMMS3_GET_RX_QUAD_TRACK_EN_DIS       MAKECMD(FMCOMMS3, 0x1C)
#define FMCOMMS3_SET_TX_ATTENUATION             MAKECMD(FMCOMMS3, 0x1D)
#define FMCOMMS3_GET_TX_ATTENUATION             MAKECMD(FMCOMMS3, 0x1E)
#define FMCOMMS3_SET_TX_RF_BANDWIDTH            MAKECMD(FMCOMMS3, 0x1F)
#define FMCOMMS3_GET_TX_RF_BANDWIDTH            MAKECMD(FMCOMMS3, 0x20)
#define FMCOMMS3_SET_TX_FIR_CONFIG              MAKECMD(FMCOMMS3, 0x21)
#define FMCOMMS3_GET_TX_FIR_CONFIG              MAKECMD(FMCOMMS3, 0x22)
#define FMCOMMS3_SET_TX_FIR_EN_DIS              MAKECMD(FMCOMMS3, 0x23)
#define FMCOMMS3_GET_TX_FIR_EN_DIS              MAKECMD(FMCOMMS3, 0x24)
#define FMCOMMS3_SET_TRX_PATH_CLKS              MAKECMD(FMCOMMS3, 0x25)
#define FMCOMMS3_GET_TRX_PATH_CLKS              MAKECMD(FMCOMMS3, 0x26)
#define FMCOMMS3_SET_DAC_DATASEL                MAKECMD(FMCOMMS3, 0x27)
#define FMCOMMS3_GET_DAC_DATASEL                MAKECMD(FMCOMMS3, 0x28)
#define FMCOMMS3_SET_DDS_FREQ                   MAKECMD(FMCOMMS3, 0x29)
#define FMCOMMS3_GET_DDS_FREQ                   MAKECMD(FMCOMMS3, 0x2A)
#define FMCOMMS3_SET_DDS_PHASE                  MAKECMD(FMCOMMS3, 0x2B)
#define FMCOMMS3_GET_DDS_PHASE                  MAKECMD(FMCOMMS3, 0x2C)
#define FMCOMMS3_SET_DDS_SCALE                  MAKECMD(FMCOMMS3, 0x2D)
#define FMCOMMS3_GET_DDS_SCALE                  MAKECMD(FMCOMMS3, 0x2E)
#define FMCOMMS3_SPI_WRITE                      MAKECMD(FMCOMMS3, 0x2F)
#define FMCOMMS3_SPI_READ                       MAKECMD(FMCOMMS3, 0x30)
#define FMCOMMS3_DIGITAL_CALIBRATION            MAKECMD(FMCOMMS3, 0x31)
#define FMCOMMS3_SET_SYNC_DELAY                 MAKECMD(FMCOMMS3, 0x32)
#define FMCOMMS3_SET_REFCLK_DELAY               MAKECMD(FMCOMMS3, 0x33)
#define FMCOMMS3_SET_SYNC_BITSLIP               MAKECMD(FMCOMMS3, 0x34)
#define FMCOMMS3_SET_SYNC_SRC                   MAKECMD(FMCOMMS3, 0x35)
#define FMCOMMS3_SOFT_SYNC                      MAKECMD(FMCOMMS3, 0x36)
#define FMCOMMS3_MCS                            MAKECMD(FMCOMMS3, 0x37)
#define FMCOMMS3_SET_MASTER_CALIB_RESULT        MAKECMD(FMCOMMS3, 0x38)
#define FMCOMMS3_SET_EXT_MASTER_CALIB_RESULT    MAKECMD(FMCOMMS3, 0x39)
#define FMCOMMS3_GET_CALIB_RESULT               MAKECMD(FMCOMMS3, 0x3A)

//RADIO640
#define RADIO640                                    0x18
#define RADIO640_PRESENCE                           MAKECMD(RADIO640, 0x1)
#define RADIO640_POWERUP                            MAKECMD(RADIO640, 0x2)
#define RADIO640_INIT                               MAKECMD(RADIO640, 0x3)
#define RADIO640_SET_EN_STATE_MACHINE_MODE          MAKECMD(RADIO640, 0x4)
#define RADIO640_GET_EN_STATE_MACHINE_MODE          MAKECMD(RADIO640, 0x5)
#define RADIO640_SET_SAMPLING_FREQ                  MAKECMD(RADIO640, 0x6)
#define RADIO640_GET_SAMPLING_FREQ                  MAKECMD(RADIO640, 0x7)
#define RADIO640_SET_TX_LO_FREQ                     MAKECMD(RADIO640, 0x8)
#define RADIO640_GET_TX_LO_FREQ                     MAKECMD(RADIO640, 0x9)
#define RADIO640_SET_RX_RF_GAIN                     MAKECMD(RADIO640, 0xA)
#define RADIO640_GET_RX_RF_GAIN                     MAKECMD(RADIO640, 0xB)
#define RADIO640_SET_RX_RF_BANDWIDTH                MAKECMD(RADIO640, 0xC)
#define RADIO640_GET_RX_RF_BANDWIDTH                MAKECMD(RADIO640, 0xD)
#define RADIO640_SET_RX_LO_FREQ                     MAKECMD(RADIO640, 0xE)
#define RADIO640_GET_RX_LO_FREQ                     MAKECMD(RADIO640, 0xF)
#define RADIO640_GET_RX_RSSI                        MAKECMD(RADIO640, 0x10)
#define RADIO640_SET_RX_GAIN_CONTROL_MODE           MAKECMD(RADIO640, 0x11)
#define RADIO640_GET_RX_GAIN_CONTROL_MODE           MAKECMD(RADIO640, 0x12)
#define RADIO640_SET_RX_FIR_CONFIG                  MAKECMD(RADIO640, 0x13)
#define RADIO640_GET_RX_FIR_CONFIG                  MAKECMD(RADIO640, 0x14)
#define RADIO640_SET_RX_FIR_EN_DIS                  MAKECMD(RADIO640, 0x15)
#define RADIO640_GET_RX_FIR_EN_DIS                  MAKECMD(RADIO640, 0x16)
#define RADIO640_SET_RX_RFDC_TRACK_EN_DIS           MAKECMD(RADIO640, 0x17)
#define RADIO640_GET_RX_RFDC_TRACK_EN_DIS           MAKECMD(RADIO640, 0x18)
#define RADIO640_SET_RX_BBDC_TRACK_EN_DIS           MAKECMD(RADIO640, 0x19)
#define RADIO640_GET_RX_BBDC_TRACK_EN_DIS           MAKECMD(RADIO640, 0x1A)
#define RADIO640_SET_RX_QUAD_TRACK_EN_DIS           MAKECMD(RADIO640, 0x1B)
#define RADIO640_GET_RX_QUAD_TRACK_EN_DIS           MAKECMD(RADIO640, 0x1C)
#define RADIO640_SET_TX_ATTENUATION                 MAKECMD(RADIO640, 0x1D)
#define RADIO640_GET_TX_ATTENUATION                 MAKECMD(RADIO640, 0x1E)
#define RADIO640_SET_TX_RF_BANDWIDTH                MAKECMD(RADIO640, 0x1F)
#define RADIO640_GET_TX_RF_BANDWIDTH                MAKECMD(RADIO640, 0x20)
#define RADIO640_SET_TX_FIR_CONFIG                  MAKECMD(RADIO640, 0x21)
#define RADIO640_GET_TX_FIR_CONFIG                  MAKECMD(RADIO640, 0x22)
#define RADIO640_SET_TX_FIR_EN_DIS                  MAKECMD(RADIO640, 0x23)
#define RADIO640_GET_TX_FIR_EN_DIS                  MAKECMD(RADIO640, 0x24)
#define RADIO640_SET_TRX_PATH_CLKS                  MAKECMD(RADIO640, 0x25)
#define RADIO640_GET_TRX_PATH_CLKS                  MAKECMD(RADIO640, 0x26)
#define RADIO640_DIGITAL_CALIBRATION                MAKECMD(RADIO640, 0x27)
#define RADIO640_SET_SYNC_OUTPUT_DELAY              MAKECMD(RADIO640, 0x28)
#define RADIO640_SET_REFCLK_DELAY                   MAKECMD(RADIO640, 0x29)
#define RADIO640_SET_SYNC_BITSLIP                   MAKECMD(RADIO640, 0x2A)
#define RADIO640_SET_SYNC_SRC                       MAKECMD(RADIO640, 0x2B)
#define RADIO640_SOFT_SYNC                          MAKECMD(RADIO640, 0x2C)
#define RADIO640_MCS                                MAKECMD(RADIO640, 0x2D)
#define RADIO640_SET_MASTER_CALIB_RESULT            MAKECMD(RADIO640, 0x2E)
#define RADIO640_SET_EXT_MASTER_CALIB_RESULT        MAKECMD(RADIO640, 0x2F)
#define RADIO640_GET_CALIB_RESULT                   MAKECMD(RADIO640, 0x30)
#define RADIO640_SET_RX_RF_FILTER                   MAKECMD(RADIO640, 0x31)
#define RADIO640_WRITE                              MAKECMD(RADIO640, 0x32)
#define RADIO640_READ                               MAKECMD(RADIO640, 0x33)
#define RADIO640_DISABLE_DESIGN_CLK                 MAKECMD(RADIO640, 0x34)
#define RADIO640_ENABLE_DESIGN_CLK                  MAKECMD(RADIO640, 0x35)
#define RADIO640_IS_CLOCK_MASTER                    MAKECMD(RADIO640, 0x36)
#define RADIO640_SET_CLK_SRC                        MAKECMD(RADIO640, 0x37)
#define RADIO640_GET_CLK_SRC                        MAKECMD(RADIO640, 0x38)
#define RADIO640_GET_BOARD_TEMP                     MAKECMD(RADIO640, 0x39)
#define RADIO640_GET_TRX_TEMP                       MAKECMD(RADIO640, 0x3A)
#define RADIO640_SET_EN_AGC_PIN_CONFIG              MAKECMD(RADIO640, 0x3B)
#define RADIO640_SET_ENABLE_PIN_CONFIG              MAKECMD(RADIO640, 0x3C)
#define RADIO640_SET_TXNRX_PIN_CONFIG               MAKECMD(RADIO640, 0x3D)
#define RADIO640_SET_CTRL_IN_PIN_CONFIG             MAKECMD(RADIO640, 0x3E)
#define RADIO640_GET_CTRL_OUT_PIN_VALUE             MAKECMD(RADIO640, 0x3F)
#define RADIO640_GET_CTRL_OUT_PIN_LOW_HIGH_VALUE    MAKECMD(RADIO640, 0x40)
#define RADIO640_SET_CTRL_OUT_CONFIG                MAKECMD(RADIO640, 0x41)
#define RADIO640_SET_POWER_MONITOR_MODE             MAKECMD(RADIO640, 0x42)
#define RADIO640_SET_POWER_MONITOR_CONVERSION_TIME  MAKECMD(RADIO640, 0x43)
#define RADIO640_SET_POWER_MONITOR_AVERAGING        MAKECMD(RADIO640, 0x44)
#define RADIO640_READ_POWER_MONITOR_BUS_VOLTAGE     MAKECMD(RADIO640, 0x45)
#define RADIO640_READ_POWER_MONITOR_BUS_POWER       MAKECMD(RADIO640, 0x46)
#define RADIO640_READ_POWER_MONITOR_BUS_CURRENT     MAKECMD(RADIO640, 0x47)
#define RADIO640_SET_TX_EXT_ATTENUATION             MAKECMD(RADIO640, 0x48)
#define RADIO640_TUNE_OSC                           MAKECMD(RADIO640, 0x49)
#define RADIO640_SET_TX_ENABLE_STATE                MAKECMD(RADIO640, 0x4A)
#define RADIO640_SET_RX_ENABLE_STATE                MAKECMD(RADIO640, 0x4B)
#define RADIO640_STORE_RX_FAST_LOCK_PROFILE         MAKECMD(RADIO640, 0x4C)
#define RADIO640_RECALL_RX_FAST_LOCK_PROFILE        MAKECMD(RADIO640, 0x4D)
#define RADIO640_LOAD_RX_FAST_LOCK_PROFILE          MAKECMD(RADIO640, 0x4E)
#define RADIO640_SAVE_RX_FAST_LOCK_PROFILE          MAKECMD(RADIO640, 0x4F)
#define RADIO640_STORE_TX_FAST_LOCK_PROFILE         MAKECMD(RADIO640, 0x51)
#define RADIO640_RECALL_TX_FAST_LOCK_PROFILE        MAKECMD(RADIO640, 0x52)
#define RADIO640_LOAD_TX_FAST_LOCK_PROFILE          MAKECMD(RADIO640, 0x53)
#define RADIO640_SAVE_TX_FAST_LOCK_PROFILE          MAKECMD(RADIO640, 0x54)
#define RADIO640_SET_RX_LO_EXT                      MAKECMD(RADIO640, 0x55)
#define RADIO640_SET_TX_LO_EXT                      MAKECMD(RADIO640, 0x56)
#define RADIO640_SET_TX_AUTO_CALIB_ENABLE           MAKECMD(RADIO640, 0x57)
#define RADIO640_GET_TX_AUTO_CALIB_ENABLE           MAKECMD(RADIO640, 0x58)
#define RADIO640_DO_CALIB                           MAKECMD(RADIO640, 0x59)
#define RADIO640_SET_SYNC_INPUT_DELAY               MAKECMD(RADIO640, 0x5A)
#define RADIO640_SET_RF_SWITCH_CONFIG               MAKECMD(RADIO640, 0x5B)
#define RADIO640_SET_TRIGGER_DELAY                  MAKECMD(RADIO640, 0x5C)
#define RADIO640_SET_TRIGGER_BITSLIP                MAKECMD(RADIO640, 0x5D)
#define RADIO640_READ_CLK_FREQ                      MAKECMD(RADIO640, 0x5E)
#define RADIO640_GET_EN_STATE_MACHINE_STATE         MAKECMD(RADIO640, 0x5F)
#define RADIO640_GET_TRIGGER_VALUE                  MAKECMD(RADIO640, 0x60)
#define RADIO640_GET_TRIGGER_LOW_HIGH_VALUE         MAKECMD(RADIO640, 0x61)
#define RADIO640_GET_INPUT_SYNC_VALUE               MAKECMD(RADIO640, 0x62)
#define RADIO640_GET_INPUT_SYNC_LOW_HIGH_VALUE      MAKECMD(RADIO640, 0x63)
#define RADIO640_SET_CLK_TO_EXTENDED_FMC_ENABLE     MAKECMD(RADIO640, 0x64)
#define RADIO640_SET_REF_OUT_ENABLE                 MAKECMD(RADIO640, 0x65)
#define RADIO640_SET_COMPLEX_MULTIPLIER             MAKECMD(RADIO640, 0x66)
#define RADIO640_GET_COMPLEX_MULTIPLIER             MAKECMD(RADIO640, 0x67)
#define RADIO640_SET_DATA_DELAY                     MAKECMD(RADIO640, 0x68)
#define RADIO640_GET_DATA_DELAY                     MAKECMD(RADIO640, 0x69)

#ifdef _MODULE_IDENT_
//FMCEEPROM and carrier info and vita related functions
#define FMCEEPROM 0x50
#define FMCEEPROM_EEPROM_READ MAKECMD(FMCEEPROM, 0x1)
#define FMCEEPROM_EEPROM_WRITE MAKECMD(FMCEEPROM, 0x2)
#define FMCEEPROM_EEPROM_GET_IDSTRING MAKECMD(FMCEEPROM, 0x3)
#define FMCEEPROM_EEPROM_GET_BOARD_STATE MAKECMD(FMCEEPROM, 0x4)
#define FMCEEPROM_EEPROM_GET_BOARD_TYPE MAKECMD(FMCEEPROM, 0x5)
#define FMCEEPROM_EEPROM_GET_CORE MAKECMD(FMCEEPROM, 0x6)
#define FMCEEPROM_EEPROM_GET_CARRIERVADJ MAKECMD(FMCEEPROM, 0x7)
#define FMCEEPROM_EEPROM_GET_PARTNUM MAKECMD(FMCEEPROM, 0x8)
#define FMCEEPROM_EEPROM_GET_SERIALNUM MAKECMD(FMCEEPROM, 0x9)
#define FMCEEPROM_EEPROM_GET_HARDREV MAKECMD(FMCEEPROM, 0xA)
#define FMCEEPROM_EEPROM_GET_FIRMREV MAKECMD(FMCEEPROM, 0xB)
#define FMCEEPROM_EEPROM_GET_MODVADJ MAKECMD(FMCEEPROM, 0xC)
#define FMCEEPROM_EEPROM_GET_MANUF MAKECMD(FMCEEPROM, 0xD)
#define FMCEEPROM_EEPROM_GET_CORENAME MAKECMD(FMCEEPROM, 0xE)
#define FMCEEPROM_EEPROM_WIPE MAKECMD(FMCEEPROM, 0xF)
#endif

//OS CONFIG
#define OSCONFIG 0x54
#define OSCONFIG_UNSET_PARAMETER MAKECMD(OSCONFIG, 0x10)
#define OSCONFIG_GET_FIRST_PARAMETER MAKECMD(OSCONFIG, 0x11)
#define OSCONFIG_GET_NEXT_PARAMETER MAKECMD(OSCONFIG, 0x12)
#define OSCONFIG_GET_PARAMETER_VALUE MAKECMD(OSCONFIG, 0x21)
#define OSCONFIG_SET_PARAMETER_VALUE MAKECMD(OSCONFIG, 0x22)
#define OSCONFIG_LOAD_FILE MAKECMD(OSCONFIG, 0x31)
#define OSCONFIG_SAVE_FILE MAKECMD(OSCONFIG, 0x32)
#define OSCONFIG_CLEAR_FILE MAKECMD(OSCONFIG, 0x33)
#define OSCONFIG_APPLY_FILE MAKECMD(OSCONFIG, 0x34)
#define OSCONFIG_SELECT_FILE MAKECMD(OSCONFIG, 0x35)
#define OSCONFIG_GET_FIRST_FILE MAKECMD(OSCONFIG, 0x41)
#define OSCONFIG_GET_NEXT_FILE MAKECMD(OSCONFIG, 0x42)

//ERRORS
enum CCE_error {
    CCEOK       = MAKE_RESULT(LYR_SEVERITY_SUCCESS, MODULE_ADP_CCE, 0),
    CCETCPERROR = MAKE_RESULT(LYR_SEVERITY_ERROR, MODULE_ADP_CCE, 1),
    CCEUNIMPLEMENTED = MAKE_RESULT(LYR_SEVERITY_ERROR, MODULE_ADP_CCE, 2),
    CCEIOCTLERROR = MAKE_RESULT(LYR_SEVERITY_ERROR, MODULE_ADP_CCE, 3),
    CCEINVALIDVALUE = MAKE_RESULT(LYR_SEVERITY_ERROR, MODULE_ADP_CCE, 4),
    CCEMEMORY = MAKE_RESULT(LYR_SEVERITY_ERROR, MODULE_ADP_CCE, 5),
    CCEBUFFER2BIG = MAKE_RESULT(LYR_SEVERITY_ERROR, MODULE_ADP_CCE, 6),
    CCEINVALIDMOD = MAKE_RESULT(LYR_SEVERITY_ERROR, MODULE_ADP_CCE, 7),
    CCEINVALIDREG = MAKE_RESULT(LYR_SEVERITY_ERROR, MODULE_ADP_CCE, 8),
    CCEINVALIDINDEX = MAKE_RESULT(LYR_SEVERITY_ERROR, MODULE_ADP_CCE, 9),
    CCEINVALIDBITSTREAM = MAKE_RESULT(LYR_SEVERITY_ERROR, MODULE_ADP_CCE, 10),
    CCEINVALIDPARTITIONTABLE = MAKE_RESULT(LYR_SEVERITY_ERROR, MODULE_ADP_CCE, 11)
};

#ifdef __cplusplus
}
#endif

#endif

